fix

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,26 +1,84 @@
 #!/usr/bin/env bash
-## Linux update and upgrade
-sudo apt update && sudo apt upgrade -y
-## need to enable a dedicated PPA with the following command
-sudo apt-get install -y --no-install-recommends software-properties-common
-sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
-##  Install Haproxy
-sudo apt install haproxy -y
-## Initialization the services haproxy
-sudo service haproxy start
-## Adding lines in haproxy.cfg
-##echo -e "# Configure Frontend listen all *:80 and solve with Backend" >> /etc/haproxy/haproxy.cfg
-##echo -e "frontend Frontend" >> /etc/haproxy/haproxy.cfg
-##echo -e "\tbind *:80" >> /etc/haproxy/haproxy.cfg
-##echo -e "\tmode http" >> /etc/haproxy/haproxy.cfg
-##echo -e "\tdefault_backend Backend" >> /etc/haproxy/haproxy.cfg
-##echo -e "# Configure the list the all server" >> /etc/haproxy/haproxy.cfg
-##echo -e "backend Backend" >> /etc/haproxy/haproxy.cfg
-##echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
-##echo -e "\tserver 3377-web-01 34.74.254.2:80 check" >> /etc/haproxy/haproxy.cfg
-##echo -e "\tserver 3377-web-02 52.207.225.1:80 check" >> /etc/haproxy/haproxy.cfg
-sed -i "$ a frontend Frontend\n\tbind *:80\n\tmode http\n\tdefault_backend Backend\nbackend Backend\n\tbalance roundrobin\n\tserver 3377-web-01 34.74.254.2:80 check\n\tserver 3377-web-02 52.207.225.1:80 check" /etc/haproxy/haproxy.cfg
-## Restart services haproxy
-sudo service haproxy restart
-## Linux update && upgrade
-sudo apt update && sudo apt upgrade -y
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
+
+# uncomment to see the script run in action
+#set -x
+
+echo -e "Updating and doing some minor checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
